version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend/notes-app-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/notes-app-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://user:password@localhost:5432/notesdb