FROM python:3.10

# Set the working directory
WORKDIR /notes

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Run the tests
CMD ["python", "-m", "unittest", "discover", "-s", "tests"]