# Generated by Django 5.1.4 on 2025-01-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_notes/'),
        ),
    ]
